# Generated by Django 5.0.6 on 2025-10-07 14:06

from django.db import migrations

def seed_properties(apps, schema_editor):
    Property = apps.get_model('core', 'Property')
    Property.objects.create(
        title="Spacious Downtown Loft",
        description="A beautiful and spacious loft in the heart of downtown.",
        price=1200000,
        bedrooms=2,
        bathrooms=2,
        sqft=1500,
        property_type="Loft",
        city="Metropolis",
        image_url="https://example.com/loft.jpg"
    )
    Property.objects.create(
        title="Cozy Suburban Home",
        description="A cozy home in a quiet suburban neighborhood.",
        price=750000,
        bedrooms=3,
        bathrooms=2,
        sqft=1800,
        property_type="House",
        city="Smallville",
        image_url="https://example.com/house.jpg"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_properties),
    ]
